### PR TITLE
fix: improved error handling

### LINKED ISSUE #57: Rollback of repo fails when repo was never initialised
## Describe the bug
If an issue arises during the AzureDevOps sub-generator before the repo is initialised, the rollback of the repo fails before it expects the repo to exist. 

## To reproduce
In this scenario, the auth token did not have the correct permissions which failed the creation of variable groups. 

## Expected behaviour
Rollback to be successful, skipping the deletion of `./.git` folder. 

## Screenshots
```
Setting up Azure DevOps...
Generating variable groups...
Creating CI Environment - Core variable group...
Creating Integration Tests - Core variable group...
Package generator encountered an error.
Rolling back all generated objects in Orion...
Rolling back 0 repositories...
Rolling back 0 build definitions...
Rolling back 0 releases definitions...
Rolling back 0 variable groups...
Rolling back 0 extensions...
Rolling back 0 service connections...
(node:23436) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Error @capgeminiuk/powerapps-project:azuredevops
ENOENT: no such file or directory, stat 'C:\.git'
```

## Environment (please complete the following information):
 - yo version
 - generator-powerapps-project version
 - Power Apps CLI version
 - Power Apps environment version

### PR DESCRIPTION
**Pull request by tdashworth**
## Purpose
_Describe the problem or feature in addition to a link to the issue(s)._
Resolves #57 and #58.

## Approach
_How does this change address the problem?_
- Checks the `./.git` folder exists before attempting to delete it.
- Catches errors during rollback and presents both to the user.

## TODOs
- [x] Documentation updated (if required)
- [x] Build and tests successful

### CODE REVIEW

File: src/generators/azuredevops/index.ts [hunk 1]
```diff
@@ -151,10 +152,16 @@ class Main extends Generator {
...
+    } catch (scaffoldError) {
+      this.log(chalk.red('Package generator encountered an error.'));
+      try {
+        await scaffolder.rollback(this.answers.adoProject);
+      } catch (rollbackError) {
+        this.log(chalk.red('Rollback failed: '));
+        this.log(chalk.red(rollbackError as string));
+        this.log(chalk.red('--------------------------------------'));
+      }
+      this.log(chalk.red(scaffoldError as string));
```
Comment (satyarkar) [inline src/generators/azuredevops/index.ts:164]: @tdashworth - can you move up the line 164, scaffold error log to, after line 156. Also it would be good to add a prefix string for both scaffold error log and rollback error log(line 161) to clearly distinguish the error was due to scaffold or rollback.

Comment (tdashworth) [reply src/generators/azuredevops/index.ts]: I've reordered the error messages but I've skipped the prefixing as I believe the separate logs should be enough.

**Review by satyarkar — APPROVED** [review]
Looks good!

**Comment by tdashworth** [comment]
@satyarkar Another review please, missed some linting issues.

**Review by satyarkar — APPROVED** [review]
I overlooked the double quote in the review. Approved!
