### PR TITLE
fix: wait for extensions to install (#51)

### LINKED ISSUE #51: Fails to create Service Connection
## Describe the bug
When running the Azure DevOps generator, it fails with the below error.

## To reproduce
Run the Azure DevOps generator. 

## Expected behaviour
Service Connection to be created.

## Screenshots
```
Error: Unable to find service connection type 'powerplatform-spn' using authentication scheme 'None'.
    at RestClient.<anonymous> (C:\code\capgemini\powerapps-project-template\node_modules\typed-rest-client\RestClient.js:200:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\capgemini\powerapps-project-template\node_modules\typed-rest-client\RestClient.js:6:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  statusCode: 400,
  result: {
    '$id': '1',
    innerException: null,
    message: "Unable to find service connection type 'powerplatform-spn' using authentication scheme 'None'.",
    typeName: 'Microsoft.VisualStudio.Services.ServiceEndpoints.WebApi.ServiceEndpointException, Microsoft.VisualStudio.Services.ServiceEndpoints.WebApi',
    typeKey: 'ServiceEndpointException',
    errorCode: 0,
    eventId: 3000
  }
}
```

## Environment (please complete the following information):
 - yo version
 - generator-powerapps-project version
 - Power Apps CLI version
 - Power Apps environment version

## Additional context
_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by tdashworth**
## Purpose
To fix #51.

## Approach
Add a 1-minute wait after installing extensions.

## TODOs
- [x] Documentation updated (if required)
- [ ] Build and tests successful

### CODE REVIEW

File: src/generators/azuredevops/generator/ExtensionGenerator.ts [hunk 1]
```diff
@@ -30,13 +31,19 @@ export default class ExtensionGenerator implements IGenerator<{ publisher: strin
...
     const installPromises: Array<Promise<void> | undefined> = uninstalledEntensions
       .map((extension) => this.installExtension(extension.publisher, extension.name));
 
-    return Promise.all(installPromises);
+    await Promise.all(installPromises);
+
+    if (installPromises.length > 0) {
+      this.log('Waiting 1 minute for the extension(s) to fully install.');
+      const ONE_MINUTE = 1 * 60 * 1000;
+      await sleep(ONE_MINUTE);
```
Comment (ewingjm) [inline src/generators/azuredevops/generator/ExtensionGenerator.ts:45]: Polling `this.conn.getInstalledExtensions()` doesn't work for this one right?

Comment (tdashworth) [reply src/generators/azuredevops/generator/ExtensionGenerator.ts:45]: Yeah, we tried that before 😞

Comment (ewingjm) [reply src/generators/azuredevops/generator/ExtensionGenerator.ts:45]: Ah, I remember that now. Just checking 🙂

**Review by ewingjm — APPROVED** [review]
